name: Pull Request Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run mill tests
        run: ./mill __.test
      - name: Compile Scala 2.13 with sbt
        run: sbt ++2.13 compile bench/compile bench/jmh:compile
      - name: Compile Scala 2.13 with sbt
        run: sbt compile bench/compile bench/jmh:compile
      - name: Run sbt tests (Scala 2.13)
        run: sbt ++2.13 test
      - name: Run sbt tests (Scala 3)
        run: sbt test
